package com.opencredo.concursus.demos.game.domain;

public enum Card {
    MYSTIC_HEDGEHOG,
    ANNOYING_ORC,
    WALL_OF_HECK,
    MAGIC_MARKER,
    SHIELD_OF_ACHILLES,
    RANCOROUS_HOBBIT,
    BILGE_BEAST,
    TOWER_OF_BEFUDDLEMENT,
    RADIO_WYVERN,
    BARBELITH,
    NECROTIC_TOXICITY,
    CHAOS_BADGER,
    MEME_MASTER,
    MINIATURE_BALROG,
    DISCO_STU,
    DEMI_ARCHON,
    HOUSE_ELF,
    DRUM_SOLO,
    TORNADO_OF_SOULS,
    HERBAL_CHARLATAN,
    ANGEL_SUMMONER,
    BMX_BANDIT,
    RAMPAGING_ENTWIFE,
    VAMPIRE_WALRUS,
    PICK_OF_DESTINY
}
